In [10]:
import numpy as np

In [ ]:
NUMPY INDEXING AND SLICING OF VECTORS 

In [13]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[6]

np.int64(17)

In [18]:
slice = arr[1:5]

slice[1] = 3

In [19]:
arr

array([11, 12,  3, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
NUMPY INDEXING AND SLICING OF MATRIX 

In [26]:
arr = np.arange(10, 40).reshape(6,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [27]:
arr[4]  # row slicing  

array([30, 31, 32, 33, 34])

In [39]:
arr[:,2 ]    # column slicing 

array([12, 17, 22, 27, 32, 37])

In [29]:
arr[2,1]   # element slicing from matrix 

np.int64(21)

In [31]:
arr[0:2, 1:3]   # sub-matrix slicing from matrix 

array([[11, 12],
       [16, 17]])

In [36]:
slice = arr[0:2, 1:3]
slice[0,0] = 5                       #if we change any part of sliced matrix it will also reflect to main matrix 

In [35]:
arr


array([[10,  5, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [37]:
arr[3:6, 3:5]   # sub-matrix slicing from main matrix 


array([[28, 29],
       [33, 34],
       [38, 39]])

In [ ]:
BOOLEAN INDEXING 

In [41]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
bool_index = arr %2 == 0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [50]:
arr = arr[bool_index]
arr

array([10, 12, 14, 16, 18])