In [2]:
import numpy as np 

In [ ]:
ARRAY OPERATIONS 

In [ ]:
Arithmetic operations 

In [4]:
a1 = np.arange(1, 5)
a2 = np.arange(5,9)


In [5]:
a1 + a2

array([ 6,  8, 10, 12])

In [6]:
a1-a2

array([-4, -4, -4, -4])

In [7]:
a1 /a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0])

In [9]:
a1 ** a2

array([    1,    64,  2187, 65536])

In [ ]:
Broadcasting 

In [10]:
l = [ 6,  8, 10, 12]
arr = np.array(l)

In [ ]:
l +10 # not possible with list 

In [12]:
arr+10  # possible with array 

array([16, 18, 20, 22])

In [ ]:
Deep and shallow copy 

In [13]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [14]:
a = arr[3:4]
a[0] = 5

In [15]:
arr  

array([1, 2, 3, 5])

In [16]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = arr[2:5]
slice= slice *10
slice


array([30, 40, 50])

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
shallow copy 

In [19]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [20]:
b = a.copy()
b[1] = 10
b

array([ 1, 10,  3,  4,  5])

In [21]:
a

array([1, 2, 3, 4, 5])

In [ ]:
Matrix operation

In [22]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(4,8).reshape(2,2)

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[4, 5],
       [6, 7]])

In [25]:
A @ B  # matrix multiplication

array([[16, 19],
       [36, 43]])

In [26]:
np.dot(A,B)

array([[16, 19],
       [36, 43]])

In [27]:
A

array([[1, 2],
       [3, 4]])

In [28]:
A.T      # transpose

array([[1, 3],
       [2, 4]])

In [ ]:
Advance array manupulation 

In [ ]:
Stacking array 

In [31]:
a = np.array([1,2,3,4,5])

In [32]:
b = np.array([6,7,8,9,0])

In [33]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [35]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [ ]:
Spliting array 

In [37]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [44]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]