In [1]:
import numpy as np

In [ ]:
Basic array creation

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
a = [1, 2, 3, 4.5, 'hello']
a

[1, 2, 3, 4.5, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [ ]:
1D array

In [7]:
l = [[1,2,3] , [5,6,7],[4,8,9]]
l

[[1, 2, 3], [5, 6, 7], [4, 8, 9]]

In [ ]:
2D array

In [8]:
np.array(l)

array([[1, 2, 3],
       [5, 6, 7],
       [4, 8, 9]])

In [ ]:
Array Generation

In [ ]:
1D ayyar 

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
2D array

In [ ]:
Zeroes generation 

In [16]:
ar = np.zeros(6)
ar

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.rand(5)

array([0.7779061 , 0.83008059, 0.7888237 , 0.98413461, 0.01778863])

In [21]:
np.random.randn(10)

array([-0.23244385,  0.34147377,  0.09461784, -1.38884571,  0.62627476,
        1.20403205,  2.61906812, -0.61892486,  0.05177348,  1.4134396 ])

In [29]:
matrix = np.random.randint(10, 50,[4,5])
matrix


array([[34, 34, 48, 37, 40],
       [36, 10, 47, 11, 49],
       [12, 10, 19, 42, 24],
       [17, 16, 37, 24, 37]], dtype=int32)

In [30]:
matrix.shape  # gives the number of columns and rows

(4, 5)

In [31]:
matrix.size     # give the no. of element present in the array 

20

In [32]:
matrix.dtype   # tells the type of matrix

dtype('int32')

In [ ]:
ARRAY METHODS

In [40]:
matrix.min()

np.int32(10)

In [37]:
matrix.max()

np.int32(49)

In [38]:
matrix.sum()

np.int64(584)

In [41]:
np.sum(matrix, axis = 0 )

array([ 99,  70, 151, 114, 150])

In [42]:
np.sum(matrix, axis = 1 )

array([193, 153, 107, 131])

In [43]:
matrix.argmax()

np.int64(9)

In [44]:
matrix.argmin()

np.int64(6)

In [ ]:
Reshaping and resizing 

In [47]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr = arr.reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])